### ISSUE TITLE
A little bug when my mouse move out from the top of the dock

### ISSUE THREAD

**Issue by jasonliao** [monkindey/dock#1]
国庆才来打台风～　f**k!

鼠标从 dock 的上方移出的时候，icons 不可以恢复原来的大小，最简单粗暴的方法就是监听 `onmouseleave` 方法，直接变回原来大小。但是过渡会很生硬～　

``` javascript
// index.js

function initEvent () {
  // ...
  dockWrap.onmouseleave = function (e) {
    for (i = 0; i < imgAmount; i++) {
      img[i].width = originalWidth[i] * 0.5;
    }
  }
}
```

师兄师兄，这届５个人，有三个师妹，快回来分享～ :smirk:

**Comment by monkindey** [comment]
哈哈，其实可以监听 document 的 `onmousemove`。

**PS：妹子在哪里？ 求爆照啊！**

**Comment by jasonliao** [comment]
@monkindey 真的，必须回来一看！

**Comment by monkindey** [comment]
@L-movingon  _求爆照_

**Comment by jasonliao** [comment]
@monkindey 没有照片给你爆，但是真的好看，不骗你～

**Comment by monkindey** [comment]
@L-movingon  有没微信呀。或者有啥qq，拉进qq群呀。
